services:
  api:
    env_file:
      - ./.env
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - type: bind
        source: ./data
        target: /data
        bind:
          create_host_path: true
networks:
  default:
    name: url-shortner-go_default
